apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment
  labels:
    app: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: nginx
        image: {{IMAGE}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
      - name: secret1