apiVersion: v1
kind: DeploymentConfig
metadata:
  name: balltest3
  namespace: {{PROJECT}}
  labels:
    app: myweb-api
spec:
  replicas: 1
  selector:
      app: myweb-api
  template:
    metadata:
      labels:
        app: myweb-api
    spec:
      containers:
      - name: myweb-api
        image: nexus.ibank.co.th/myweb-api:{{TAG_IMAGE}}
        ports:
        - containerPort: 8080
        env:
          - name: aaa
            value: bbb
          - name: ccc
            value: ddzzddd
          - name: LANG
            value: C.UTF8
      imagePullSecrets:
        - name: nexus