apiVersion: v1
kind: DeploymentConfig
metadata:
  name: balltest3
  namespace: {{PROJECT}}
  labels:
    app: balltest3
spec:
  replicas: 1
  selector:
      app: balltest3
  template:
    metadata:
      labels:
        app: balltest3
    spec:
      containers:
      - name: catalog
        image: nexus.dcocp.ibank.com/balltest3:{{TAG_IMAGE}}
        ports:
        - containerPort: 8080
        env:
          - name: aaa
            value: bbb
          - name: ccc
            value: ddzzddd
          - name: LANG
            value: C.UTF8
      imagePullSecrets:
        - name: nexus