apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-server
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  name: nexus-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8081
    name: "nexus"
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus-server
  sessionAffinity: None
  type: NodePort